package threadrelay;

/**
 * FRMPista - Finestra principale della gara di staffetta
 * Mostra la UI e delega la logica a GestoreGara
 */
public class FRMPista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FRMPista.class.getName());
    
    private GestoreGara gestore;  // Gestore della logica della gara

    /**
     * Crea la finestra all'avvio
     */
    public FRMPista() {
        initComponents();  // NetBeans genera questa GUI
        this.gestore = new GestoreGara(this);  // Crea il gestore
        initRaceControls();  // Configura i bottoni
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNLProgressBar = new javax.swing.JPanel();
        LBLAtleta1 = new javax.swing.JLabel();
        LBLAtleta2 = new javax.swing.JLabel();
        LBLAtleta3 = new javax.swing.JLabel();
        LBLAtleta4 = new javax.swing.JLabel();
        PRGSCorridore1 = new javax.swing.JProgressBar();
        PRGSCorridore2 = new javax.swing.JProgressBar();
        PRGSCorridore3 = new javax.swing.JProgressBar();
        PRGSCorridore4 = new javax.swing.JProgressBar();
        PNLBottoni = new javax.swing.JPanel();
        CMBSelezioneVelocita = new javax.swing.JComboBox<>();
        BTNAvvia = new javax.swing.JButton();
        BTNPausa = new javax.swing.JButton();
        BTNRiprendi = new javax.swing.JButton();
        BTNFerma = new javax.swing.JButton();
        PNLPosizioneCorridori = new javax.swing.JPanel();
        PNLStatCorridore1 = new javax.swing.JPanel();
        LBLCorridore1 = new javax.swing.JLabel();
        LBLAvanzamentoCorridore1 = new javax.swing.JLabel();
        PNLStatCorridore2 = new javax.swing.JPanel();
        LBLCorridore2 = new javax.swing.JLabel();
        LBLAvanzamentoCorridore2 = new javax.swing.JLabel();
        PNLStatCorridore3 = new javax.swing.JPanel();
        LBLCorridore3 = new javax.swing.JLabel();
        LBLAvanzamentoCorridore3 = new javax.swing.JLabel();
        PNLStatCorridore4 = new javax.swing.JPanel();
        LBLCorridore4 = new javax.swing.JLabel();
        LBLAvanzamentoCorridore4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relay Runners");
        setResizable(false);

        PNLProgressBar.setBorder(javax.swing.BorderFactory.createTitledBorder("Corridori"));
        PNLProgressBar.setPreferredSize(new java.awt.Dimension(1000, 391));
        PNLProgressBar.setLayout(null);

        PRGSCorridore1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PNLProgressBar.add(PRGSCorridore1);
        PRGSCorridore1.setBounds(5, 19, 990, 116);

        PNLProgressBar.add(PRGSCorridore2);
        PRGSCorridore2.setBounds(5, 185, 990, 116);

        PNLProgressBar.add(PRGSCorridore3);
        PRGSCorridore3.setBounds(5, 351, 990, 116);

        PNLProgressBar.add(PRGSCorridore4);
        PRGSCorridore4.setBounds(5, 517, 990, 116);

        LBLAtleta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/Corridore.gif")));
        PNLProgressBar.add(LBLAtleta1);
        LBLAtleta1.setBounds(10, 40, 70, 70);

        LBLAtleta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/Corridore.gif")));
        PNLProgressBar.add(LBLAtleta2);
        LBLAtleta2.setBounds(10, 210, 70, 70);

        LBLAtleta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/Corridore.gif")));
        PNLProgressBar.add(LBLAtleta3);
        LBLAtleta3.setBounds(10, 380, 70, 70);

        LBLAtleta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/Corridore.gif")));
        PNLProgressBar.add(LBLAtleta4);
        LBLAtleta4.setBounds(10, 540, 70, 70);

        getContentPane().add(PNLProgressBar, java.awt.BorderLayout.LINE_START);

        PNLBottoni.setBorder(javax.swing.BorderFactory.createTitledBorder("Comandi"));
        PNLBottoni.setPreferredSize(new java.awt.Dimension(1454, 120));
        PNLBottoni.setLayout(new java.awt.GridLayout(1, 5));

        CMBSelezioneVelocita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lento", "Spedito", "Veloce" }));
        PNLBottoni.add(CMBSelezioneVelocita);

        BTNAvvia.setText("Avvia Gara");
        PNLBottoni.add(BTNAvvia);

        BTNPausa.setText("Pausa");
        PNLBottoni.add(BTNPausa);

        BTNRiprendi.setText("Riprendi");
        PNLBottoni.add(BTNRiprendi);

        BTNFerma.setText("Ferma Gara");
        PNLBottoni.add(BTNFerma);

        getContentPane().add(PNLBottoni, java.awt.BorderLayout.PAGE_END);

        PNLPosizioneCorridori.setBorder(javax.swing.BorderFactory.createTitledBorder("Posizione Corridori"));
        PNLPosizioneCorridori.setMinimumSize(new java.awt.Dimension(310, 573));
        PNLPosizioneCorridori.setPreferredSize(new java.awt.Dimension(310, 666));
        PNLPosizioneCorridori.setLayout(new java.awt.GridLayout(4, 2, 0, 50));

        PNLStatCorridore1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PNLStatCorridore1.setLayout(new java.awt.GridLayout(1, 2));

        LBLCorridore1.setText("Corridore 1");
        PNLStatCorridore1.add(LBLCorridore1);
        PNLStatCorridore1.add(LBLAvanzamentoCorridore1);

        PNLPosizioneCorridori.add(PNLStatCorridore1);

        PNLStatCorridore2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PNLStatCorridore2.setLayout(new java.awt.GridLayout(1, 2));

        LBLCorridore2.setText("Corridore 2");
        PNLStatCorridore2.add(LBLCorridore2);
        PNLStatCorridore2.add(LBLAvanzamentoCorridore2);

        PNLPosizioneCorridori.add(PNLStatCorridore2);

        PNLStatCorridore3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PNLStatCorridore3.setLayout(new java.awt.GridLayout(1, 2));

        LBLCorridore3.setText("Corridore 3");
        PNLStatCorridore3.add(LBLCorridore3);
        PNLStatCorridore3.add(LBLAvanzamentoCorridore3);

        PNLPosizioneCorridori.add(PNLStatCorridore3);

        PNLStatCorridore4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PNLStatCorridore4.setLayout(new java.awt.GridLayout(1, 2));

        LBLCorridore4.setText("Corridore 4");
        PNLStatCorridore4.add(LBLCorridore4);
        PNLStatCorridore4.add(LBLAvanzamentoCorridore4);

        PNLPosizioneCorridori.add(PNLStatCorridore4);

        getContentPane().add(PNLPosizioneCorridori, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Configura i 4 bottoni della gara
     */
    private void initRaceControls() {
        // Imposta il massimo delle barre di progresso a 99
        int maxValue = GestoreGara.getFinishValue();
        PRGSCorridore1.setMinimum(0);
        PRGSCorridore1.setMaximum(maxValue);
        PRGSCorridore2.setMinimum(0);
        PRGSCorridore2.setMaximum(maxValue);
        PRGSCorridore3.setMinimum(0);
        PRGSCorridore3.setMaximum(maxValue);
        PRGSCorridore4.setMinimum(0);
        PRGSCorridore4.setMaximum(maxValue);

        // Bottone "Avvia Gara" - inizia la gara
        BTNAvvia.addActionListener(evt -> {
            gestore.startRace(raceSpeedMillis());
            BTNAvvia.setEnabled(false);  // Disabilita Avvia
            CMBSelezioneVelocita.setEnabled(false);  // Blocca cambio velocità
            BTNPausa.setEnabled(true);  // Abilita Pausa
            BTNRiprendi.setEnabled(false);
            BTNFerma.setEnabled(true);  // Abilita Ferma
        });
        
        // Bottone "Pausa" - ferma gli atleti
        BTNPausa.addActionListener(evt -> {
            gestore.pauseRace();
            BTNPausa.setEnabled(false);  // Disabilita Pausa
            BTNRiprendi.setEnabled(true);  // Abilita Riprendi
        });
        
        // Bottone "Riprendi" - continua la gara
        BTNRiprendi.addActionListener(evt -> {
            gestore.resumeRace();
            BTNRiprendi.setEnabled(false);  // Disabilita Riprendi
            BTNPausa.setEnabled(true);  // Abilita Pausa
        });
        
        // Bottone "Ferma Gara" - stop completo
        BTNFerma.addActionListener(evt -> {
            gestore.stopRace();
            enableControlsAfterFinish();  // Ripristina lo stato iniziale
        });

        // All'inizio, solo "Avvia" è disponibile
        BTNPausa.setEnabled(false);
        BTNRiprendi.setEnabled(false);
        BTNFerma.setEnabled(false);
        
        // Posiziona gli atleti all'inizio (dopo che tutto è renderizzato)
        javax.swing.SwingUtilities.invokeLater(this::resetRunnerProgress);
    }

    /**
     * Aggiorna la barra e la posizione di un atleta
     */
    public void updateRunnerDisplay(int index, int value) {
        int maxValue = GestoreGara.getFinishValue();
        getProgressBar(index).setValue(value);  // Aggiorna la barra
        getStatusLabel(index).setText(value < maxValue ? String.valueOf(value) : "Fine");  // Mostra il numero
        setRunnerPosition(index, value);  // Sposta l'atleta nella barra
    }

    /**
     * Resetta tutti gli atleti all'inizio
     */
    public void resetRunnerProgress() {
        for (int i = 0; i < 4; i++) {
            getProgressBar(i).setValue(0);  // Azzera la barra
            getStatusLabel(i).setText("");  // Cancella il numero
            setRunnerPosition(i, 0);  // Posiziona all'inizio
        }
    }

    /**
     * Ripristina i controlli dopo la fine della gara
     */
    public void enableControlsAfterFinish() {
        CMBSelezioneVelocita.setEnabled(true);  // Permette di cambiare velocità
        BTNAvvia.setEnabled(true);  // Permette di riavviare
        BTNPausa.setEnabled(false);
        BTNPausa.setText("Pausa");
        BTNRiprendi.setEnabled(false);
        BTNFerma.setEnabled(false);
    }

    /**
     * Restituisce i millisecondi tra un passo e l'altro in base alla velocità
     */
    private int raceSpeedMillis() {
        return switch (CMBSelezioneVelocita.getSelectedIndex()) {
            case 0 -> 120;  // Lento
            case 1 -> 60;   // Spedito
            case 2 -> 25;   // Veloce
            default -> 60;
        };
    }

    /**
     * Posiziona l'atleta nella sua barra di progresso
     * @param index quale atleta (0, 1, 2, 3)
     * @param value da quanto avanzato (0-99)
     */
    private void setRunnerPosition(int index, int value) {
        javax.swing.JLabel runnerLabel = getRunnerLabel(index);
        
        // Calcola la posizione X dell'atleta nella barra
        int startX = 10;  // Inizio della barra
        int endX = 925;   // Fine della barra
        int range = endX - startX;
        int maxValue = GestoreGara.getFinishValue();
        int x = startX + (int) Math.round(range * (value / (double) maxValue));
        
        // Calcola la posizione Y dell'atleta (una per ogni barra)
        int y = switch (index) {
            case 0 -> 40;    // Prima barra
            case 1 -> 210;   // Seconda barra
            case 2 -> 380;   // Terza barra
            case 3 -> 540;   // Quarta barra
            default -> 40;
        };
        
        // Sposta l'atleta e assicurati che sia visibile
        runnerLabel.setBounds(x, y, 70, 70);
        bringRunnerToFront(index);
    }

    /**
     * Assicura che l'atleta sia visibile sopra agli altri componenti
     */
    private void bringRunnerToFront(int index) {
        javax.swing.JLabel runnerLabel = getRunnerLabel(index);
        if (PNLProgressBar.getComponentZOrder(runnerLabel) != 0) {
            PNLProgressBar.setComponentZOrder(runnerLabel, 0);
            PNLProgressBar.repaint();
        }
    }

    /**
     * Restituisce la barra di progresso dell'atleta
     */
    private javax.swing.JProgressBar getProgressBar(int index) {
        return switch (index) {
            case 0 -> PRGSCorridore1;
            case 1 -> PRGSCorridore2;
            case 2 -> PRGSCorridore3;
            default -> PRGSCorridore4;
        };
    }

    /**
     * Restituisce l'etichetta del progresso (il numero)
     */
    private javax.swing.JLabel getStatusLabel(int index) {
        return switch (index) {
            case 0 -> LBLAvanzamentoCorridore1;
            case 1 -> LBLAvanzamentoCorridore2;
            case 2 -> LBLAvanzamentoCorridore3;
            default -> LBLAvanzamentoCorridore4;
        };
    }

    /**
     * Restituisce l'etichetta dell'atleta (l'immagine)
     */
    private javax.swing.JLabel getRunnerLabel(int index) {
        return switch (index) {
            case 0 -> LBLAtleta1;
            case 1 -> LBLAtleta2;
            case 2 -> LBLAtleta3;
            default -> LBLAtleta4;
        };
    }

    /**
     * Avvia l'applicazione
     */
    public static void main(String args[]) {
        // Imposta il tema "Nimbus" se disponibile
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        // Crea e mostra la finestra nel thread di Swing
        java.awt.EventQueue.invokeLater(() -> new FRMPista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAvvia;
    private javax.swing.JButton BTNFerma;
    private javax.swing.JButton BTNPausa;
    private javax.swing.JButton BTNRiprendi;
    private javax.swing.JComboBox<String> CMBSelezioneVelocita;
    private javax.swing.JLabel LBLAtleta1;
    private javax.swing.JLabel LBLAtleta2;
    private javax.swing.JLabel LBLAtleta3;
    private javax.swing.JLabel LBLAtleta4;
    private javax.swing.JLabel LBLAvanzamentoCorridore1;
    private javax.swing.JLabel LBLAvanzamentoCorridore2;
    private javax.swing.JLabel LBLAvanzamentoCorridore3;
    private javax.swing.JLabel LBLAvanzamentoCorridore4;
    private javax.swing.JLabel LBLCorridore1;
    private javax.swing.JLabel LBLCorridore2;
    private javax.swing.JLabel LBLCorridore3;
    private javax.swing.JLabel LBLCorridore4;
    private javax.swing.JPanel PNLBottoni;
    private javax.swing.JPanel PNLPosizioneCorridori;
    private javax.swing.JPanel PNLProgressBar;
    private javax.swing.JPanel PNLStatCorridore1;
    private javax.swing.JPanel PNLStatCorridore2;
    private javax.swing.JPanel PNLStatCorridore3;
    private javax.swing.JPanel PNLStatCorridore4;
    private javax.swing.JProgressBar PRGSCorridore1;
    private javax.swing.JProgressBar PRGSCorridore2;
    private javax.swing.JProgressBar PRGSCorridore3;
    private javax.swing.JProgressBar PRGSCorridore4;
    // End of variables declaration//GEN-END:variables
}
