/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threadrelay;

import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.SwingUtilities;

/**
 *
 * @author MoMo
 */
public class FRMPista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FRMPista.class.getName());
    private static final int RUNNERS = 4;
    private static final int FINISH = 99;
    private final Object pauseLock = new Object();
    private volatile boolean paused;
    private volatile boolean stopped;
    private final RelayRunner[] runners = new RelayRunner[RUNNERS];
    private final Thread[] runnerThreads = new Thread[RUNNERS];
    private final AtomicInteger finishedCount = new AtomicInteger();

    /**
     * Creates new form FRMPista
     */
    public FRMPista() {
        initComponents();
        setResizable(false);
        initRaceControls();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNLProgressBar = new javax.swing.JPanel();
        LBLAtleta1 = new javax.swing.JLabel();
        LBLAtleta2 = new javax.swing.JLabel();
        LBLAtleta3 = new javax.swing.JLabel();
        LBLAtleta4 = new javax.swing.JLabel();
        PRGSCorridore1 = new javax.swing.JProgressBar();
        PRGSCorridore2 = new javax.swing.JProgressBar();
        PRGSCorridore3 = new javax.swing.JProgressBar();
        PRGSCorridore4 = new javax.swing.JProgressBar();
        PNLBottoni = new javax.swing.JPanel();
        CMBSelezioneVelocita = new javax.swing.JComboBox<>();
        BTNAvvia = new javax.swing.JButton();
        BTNPausa = new javax.swing.JButton();
        BTNRiprendi = new javax.swing.JButton();
        BTNFerma = new javax.swing.JButton();
        PNLPosizioneCorridori = new javax.swing.JPanel();
        PNLStatCorridore1 = new javax.swing.JPanel();
        LBLCorridore1 = new javax.swing.JLabel();
        LBLAvanzamentoCorridore1 = new javax.swing.JLabel();
        PNLStatCorridore2 = new javax.swing.JPanel();
        LBLCorridore2 = new javax.swing.JLabel();
        LBLAvanzamentoCorridore2 = new javax.swing.JLabel();
        PNLStatCorridore3 = new javax.swing.JPanel();
        LBLCorridore3 = new javax.swing.JLabel();
        LBLAvanzamentoCorridore3 = new javax.swing.JLabel();
        PNLStatCorridore4 = new javax.swing.JPanel();
        LBLCorridore4 = new javax.swing.JLabel();
        LBLAvanzamentoCorridore4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relay Runners");
        setResizable(false);

        PNLProgressBar.setBorder(javax.swing.BorderFactory.createTitledBorder("Corridori"));
        PNLProgressBar.setPreferredSize(new java.awt.Dimension(1000, 391));
        PNLProgressBar.setLayout(null);

        LBLAtleta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/Corridore.gif"))); // NOI18N
        PNLProgressBar.add(LBLAtleta1);
        LBLAtleta1.setBounds(10, 40, 70, 70);

        LBLAtleta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/Corridore.gif"))); // NOI18N
        PNLProgressBar.add(LBLAtleta2);
        LBLAtleta2.setBounds(10, 210, 70, 70);

        LBLAtleta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/Corridore.gif"))); // NOI18N
        PNLProgressBar.add(LBLAtleta3);
        LBLAtleta3.setBounds(10, 380, 70, 70);

        LBLAtleta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/Corridore.gif"))); // NOI18N
        PNLProgressBar.add(LBLAtleta4);
        LBLAtleta4.setBounds(10, 540, 70, 70);

        PRGSCorridore1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PNLProgressBar.add(PRGSCorridore1);
        PRGSCorridore1.setBounds(5, 19, 990, 116);
        PNLProgressBar.add(PRGSCorridore2);
        PRGSCorridore2.setBounds(5, 185, 990, 116);
        PNLProgressBar.add(PRGSCorridore3);
        PRGSCorridore3.setBounds(5, 351, 990, 116);
        PNLProgressBar.add(PRGSCorridore4);
        PRGSCorridore4.setBounds(5, 517, 990, 116);

        getContentPane().add(PNLProgressBar, java.awt.BorderLayout.LINE_START);

        PNLBottoni.setBorder(javax.swing.BorderFactory.createTitledBorder("Comandi"));
        PNLBottoni.setPreferredSize(new java.awt.Dimension(1454, 120));
        PNLBottoni.setLayout(new java.awt.GridLayout(1, 5));

        CMBSelezioneVelocita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lento", "Spedito", "Veloce" }));
        PNLBottoni.add(CMBSelezioneVelocita);

        BTNAvvia.setText("Avvia Gara");
        PNLBottoni.add(BTNAvvia);

        BTNPausa.setText("Pausa");
        PNLBottoni.add(BTNPausa);

        BTNRiprendi.setText("Riprendi");
        PNLBottoni.add(BTNRiprendi);

        BTNFerma.setText("Ferma Gara");
        PNLBottoni.add(BTNFerma);

        getContentPane().add(PNLBottoni, java.awt.BorderLayout.PAGE_END);

        PNLPosizioneCorridori.setBorder(javax.swing.BorderFactory.createTitledBorder("Posizione Corridori"));
        PNLPosizioneCorridori.setMinimumSize(new java.awt.Dimension(310, 573));
        PNLPosizioneCorridori.setPreferredSize(new java.awt.Dimension(310, 666));
        PNLPosizioneCorridori.setLayout(new java.awt.GridLayout(4, 2, 0, 50));

        PNLStatCorridore1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PNLStatCorridore1.setToolTipText("");
        PNLStatCorridore1.setLayout(new java.awt.GridLayout(1, 2));

        LBLCorridore1.setText("Corridore 1");
        PNLStatCorridore1.add(LBLCorridore1);
        PNLStatCorridore1.add(LBLAvanzamentoCorridore1);

        PNLPosizioneCorridori.add(PNLStatCorridore1);

        PNLStatCorridore2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PNLStatCorridore2.setLayout(new java.awt.GridLayout(1, 2));

        LBLCorridore2.setText("Corridore 2");
        PNLStatCorridore2.add(LBLCorridore2);
        PNLStatCorridore2.add(LBLAvanzamentoCorridore2);

        PNLPosizioneCorridori.add(PNLStatCorridore2);

        PNLStatCorridore3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PNLStatCorridore3.setLayout(new java.awt.GridLayout(1, 2));

        LBLCorridore3.setText("Corridore 3");
        PNLStatCorridore3.add(LBLCorridore3);
        PNLStatCorridore3.add(LBLAvanzamentoCorridore3);

        PNLPosizioneCorridori.add(PNLStatCorridore3);

        PNLStatCorridore4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PNLStatCorridore4.setLayout(new java.awt.GridLayout(1, 2));

        LBLCorridore4.setText("Corridore 4");
        PNLStatCorridore4.add(LBLCorridore4);
        PNLStatCorridore4.add(LBLAvanzamentoCorridore4);

        PNLPosizioneCorridori.add(PNLStatCorridore4);

        getContentPane().add(PNLPosizioneCorridori, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initRaceControls() {
        PRGSCorridore1.setMinimum(0);
        PRGSCorridore1.setMaximum(FINISH);
        PRGSCorridore2.setMinimum(0);
        PRGSCorridore2.setMaximum(FINISH);
        PRGSCorridore3.setMinimum(0);
        PRGSCorridore3.setMaximum(FINISH);
        PRGSCorridore4.setMinimum(0);
        PRGSCorridore4.setMaximum(FINISH);

        BTNAvvia.addActionListener(evt -> startRace());
        BTNPausa.addActionListener(evt -> pauseRace());
        BTNRiprendi.addActionListener(evt -> resumeRace());
        BTNFerma.addActionListener(evt -> stopRace());

        BTNPausa.setEnabled(false);
        BTNRiprendi.setEnabled(false);
        BTNFerma.setEnabled(false);

        resetRace();
    }

    private void resetRace() {
        paused = false;
        stopped = false;
        finishedCount.set(0);

        SwingUtilities.invokeLater(() -> {
            LBLAvanzamentoCorridore1.setText("");
            LBLAvanzamentoCorridore2.setText("");
            LBLAvanzamentoCorridore3.setText("");
            LBLAvanzamentoCorridore4.setText("");

            PRGSCorridore1.setValue(0);
            PRGSCorridore2.setValue(0);
            PRGSCorridore3.setValue(0);
            PRGSCorridore4.setValue(0);

            setRunnerPosition(0, 0);
            setRunnerPosition(1, 0);
            setRunnerPosition(2, 0);
            setRunnerPosition(3, 0);
        });
    }

    private void startRace() {
        resetRace();
        CMBSelezioneVelocita.setEnabled(false);
        BTNAvvia.setEnabled(false);
        BTNPausa.setEnabled(true);
        BTNRiprendi.setEnabled(false);
        BTNFerma.setEnabled(true);

        int speedMillis = raceSpeedMillis();

        for (int i = 0; i < RUNNERS; i++) {
            runners[i] = new RelayRunner(i, speedMillis);
            runnerThreads[i] = new Thread(runners[i], "Runner-" + (i + 1));
        }

        if (runnerThreads[0] != null) {
            runnerThreads[0].start();
        }
    }

    private void pauseRace() {
        if (!paused && !stopped) {
            paused = true;
            BTNPausa.setEnabled(false);
            BTNRiprendi.setEnabled(true);
        }
    }

    private void resumeRace() {
        if (paused && !stopped) {
            synchronized (pauseLock) {
                paused = false;
                pauseLock.notifyAll();
            }
            BTNPausa.setEnabled(true);
            BTNRiprendi.setEnabled(false);
        }
    }

    private void stopRace() {
        stopped = true;
        paused = false;
        synchronized (pauseLock) {
            pauseLock.notifyAll();
        }

        BTNPausa.setEnabled(false);
        BTNRiprendi.setEnabled(false);
        BTNFerma.setEnabled(false);
        CMBSelezioneVelocita.setEnabled(true);
        BTNAvvia.setEnabled(true);
    }

    private void enableControlsAfterFinish() {
        CMBSelezioneVelocita.setEnabled(true);
        BTNAvvia.setEnabled(true);
        BTNPausa.setEnabled(false);
        BTNRiprendi.setEnabled(false);
        BTNFerma.setEnabled(false);
    }

    private void startNextRunner(int currentIndex) {
        int nextIndex = currentIndex + 1;
        if (nextIndex < RUNNERS && !stopped) {
            Thread nextThread = runnerThreads[nextIndex];
            if (nextThread != null && !nextThread.isAlive()) {
                nextThread.start();
            }
        }
    }

    private void updateRunnerProgress(int index, int value) {
        SwingUtilities.invokeLater(() -> {
            getProgressBar(index).setValue(value);
            getStatusLabel(index).setText(value < FINISH ? String.valueOf(value) : "Fine");
            setRunnerPosition(index, value);
        });
    }

    private void setRunnerPosition(int index, int value) {
        javax.swing.JLabel runnerLabel = getRunnerLabel(index);
        javax.swing.JProgressBar progressBar = getProgressBar(index);
        int trackX = progressBar.getX();
        int trackWidth = progressBar.getWidth();
        int runnerWidth = runnerLabel.getWidth();
        int x = trackX + (int) Math.round((trackWidth - runnerWidth) * (value / (double) FINISH));
        int y = progressBar.getY() + (progressBar.getHeight() - runnerLabel.getHeight()) / 2;
        runnerLabel.setBounds(x, y, runnerWidth, runnerLabel.getHeight());
        bringRunnerToFront(index);
    }

    private void bringRunnerToFront(int index) {
        javax.swing.JLabel runnerLabel = getRunnerLabel(index);
        if (PNLProgressBar.getComponentZOrder(runnerLabel) != 0) {
            PNLProgressBar.setComponentZOrder(runnerLabel, 0);
            PNLProgressBar.repaint();
        }
    }

    private javax.swing.JProgressBar getProgressBar(int index) {
        switch (index) {
            case 0:
                return PRGSCorridore1;
            case 1:
                return PRGSCorridore2;
            case 2:
                return PRGSCorridore3;
            case 3:
            default:
                return PRGSCorridore4;
        }
    }

    private javax.swing.JLabel getStatusLabel(int index) {
        switch (index) {
            case 0:
                return LBLAvanzamentoCorridore1;
            case 1:
                return LBLAvanzamentoCorridore2;
            case 2:
                return LBLAvanzamentoCorridore3;
            case 3:
            default:
                return LBLAvanzamentoCorridore4;
        }
    }

    private javax.swing.JLabel getRunnerLabel(int index) {
        switch (index) {
            case 0:
                return LBLAtleta1;
            case 1:
                return LBLAtleta2;
            case 2:
                return LBLAtleta3;
            case 3:
            default:
                return LBLAtleta4;
        }
    }

    private int raceSpeedMillis() {
        switch (CMBSelezioneVelocita.getSelectedIndex()) {
            case 0:
                return 120;
            case 1:
                return 60;
            case 2:
                return 25;
            default:
                return 60;
        }
    }

    private void runnerDone() {
        if (finishedCount.incrementAndGet() == RUNNERS) {
            SwingUtilities.invokeLater(this::enableControlsAfterFinish);
        }
    }

    private class RelayRunner implements Runnable {
        private final int index;
        private final int stepMillis;
        private int count;

        RelayRunner(int index, int stepMillis) {
            this.index = index;
            this.stepMillis = stepMillis;
            this.count = 0;
        }

        @Override
        public void run() {
            updateRunnerProgress(index, count);
            while (!stopped && count < FINISH) {
                if (count == 90 && index < RUNNERS - 1) {
                    startNextRunner(index);
                }

                try {
                    Thread.sleep(stepMillis);
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                    break;
                }

                synchronized (pauseLock) {
                    while (paused && !stopped) {
                        try {
                            pauseLock.wait();
                        } catch (InterruptedException ex) {
                            Thread.currentThread().interrupt();
                            stopped = true;
                            break;
                        }
                    }
                }

                if (stopped) {
                    break;
                }

                count++;
                updateRunnerProgress(index, count);
            }

            if (!stopped && count >= FINISH) {
                runnerDone();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FRMPista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAvvia;
    private javax.swing.JButton BTNFerma;
    private javax.swing.JButton BTNPausa;
    private javax.swing.JButton BTNRiprendi;
    private javax.swing.JComboBox<String> CMBSelezioneVelocita;
    private javax.swing.JLabel LBLAtleta1;
    private javax.swing.JLabel LBLAtleta2;
    private javax.swing.JLabel LBLAtleta3;
    private javax.swing.JLabel LBLAtleta4;
    private javax.swing.JLabel LBLAvanzamentoCorridore1;
    private javax.swing.JLabel LBLAvanzamentoCorridore2;
    private javax.swing.JLabel LBLAvanzamentoCorridore3;
    private javax.swing.JLabel LBLAvanzamentoCorridore4;
    private javax.swing.JLabel LBLCorridore1;
    private javax.swing.JLabel LBLCorridore2;
    private javax.swing.JLabel LBLCorridore3;
    private javax.swing.JLabel LBLCorridore4;
    private javax.swing.JPanel PNLBottoni;
    private javax.swing.JPanel PNLPosizioneCorridori;
    private javax.swing.JPanel PNLProgressBar;
    private javax.swing.JPanel PNLStatCorridore1;
    private javax.swing.JPanel PNLStatCorridore2;
    private javax.swing.JPanel PNLStatCorridore3;
    private javax.swing.JPanel PNLStatCorridore4;
    private javax.swing.JProgressBar PRGSCorridore1;
    private javax.swing.JProgressBar PRGSCorridore2;
    private javax.swing.JProgressBar PRGSCorridore3;
    private javax.swing.JProgressBar PRGSCorridore4;
    // End of variables declaration//GEN-END:variables
}
